no message

diff --git a/modules/dns/bin/cld-setdns b/modules/dns/bin/cld-setdns
--- a/modules/dns/bin/cld-setdns
+++ b/modules/dns/bin/cld-setdns
@@ -20,15 +20,15 @@ cf-dns-api-creds
 CF_ZONE_ID=$(cf-dns-get-zone-id ${MAIN_ZONE})
 test ${CF_ZONE_ID} && break
 done
-test $CF_ZONE_ID || echo domain ${MAIN_ZONE} not found in known accounts - trying to add
+test $CF_ZONE_ID || echo "domain $MAIN_ZONE not found in known accounts - trying to add"
 test $CF_ZONE_ID || cf-dns-define-cf-api 
 test $CF_ZONE_ID || cf-dns-api-creds
 
 test $CF_ZONE_ID || for ITTER in $(seq 1 10)
 do
 CF_ZONE_ID=$(cf-dns-domain-add ${MAIN_ZONE})
-test ${CF_ZONE_ID} || CF_ZONE_ID=$(cf-dns-get-zone-id ${MAIN_ZONE})
-test $CF_ZONE_ID && echo domain ${MAIN_ZONE} successfully added to account ${CFACC}
+test $CF_ZONE_ID || CF_ZONE_ID=$(cf-dns-get-zone-id ${MAIN_ZONE})
+test $CF_ZONE_ID && echo "domain $MAIN_ZONE successfully added to account $CFACC"
 test $CF_ZONE_ID && break
 done
 
